### PR TITLE
Account for v1 backing accounts when creating first admin

### PR DESCRIPTION
**Pull request by JuneKelly**
This gets launchpad to work in the contemporary dev environment.

### CODE REVIEW

**Comment by gh2k** [comment]
Looks OK to me, but could you add a test?

**Review by gh2k — CHANGES_REQUESTED** [review]
Looks OK, but could you add a test?

**Review by paulojreis — APPROVED** [review]
LGTM

Needs https://github.com/sharelatex/sharelatex-dev-environment/pull/131 merged to work out-of-the-box in the local dev env.

**Comment by JuneKelly** [comment]
@gh2k, test added :+1:

**Review by gh2k — APPROVED** [review]
Thanks! :+1:

**Pull request merged**
